services:
  # PHP Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sincronizacao-app
    container_name: sincronizacao-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - sincronizacao-network

  # Nginx Service
  nginx:
    image: nginx:stable-alpine
    container_name: sincronizacao-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./docker-config/nginx:/etc/nginx/conf.d
    networks:
      - sincronizacao-network
    depends_on:
      - app

networks:
  sincronizacao-network:
    driver: bridge
